# Sample configuration for teranode-p2p
p2p:
  bootstrap_addresses:
    - "/dns4/teranode-bootstrap.bsvb.tech/tcp/9901/p2p/12D3KooWESmhNAN8s6NPdGNvJH3zJ4wMKDxapXKNUe2DzkAwKYqK"
    - "/dns4/teranode-bootstrap-stage.bsvb.tech/tcp/9901/p2p/12D3KooWJ6kQHAR65xkA34NABsNVAJyVxPWh8JUSo1vtZsTyw4GD"
  shared_key: "285b49e6d910726a70f205086c39cbac6d8dcc47839053a21b1f614773bbc137"
  dht_protocol_id: "/teranode"
  port: 9901
  listen_addresses:
    - "127.0.0.1"
  advertise: true
  use_private_dht: true

database:
  path: "./teranode-p2p.db"

topics:
  - "bitcoin/mainnet-bestblock"
  - "bitcoin/mainnet-block"
  - "bitcoin/mainnet-subtree"
  - "bitcoin/mainnet-mining_on"
  - "bitcoin/mainnet-handshake"
  - "bitcoin/mainnet-rejected_tx"
  - "bitcoin/testnet-bestblock"
  - "bitcoin/testnet-block"
  - "bitcoin/testnet-subtree"
  - "bitcoin/testnet-mining_on"
  - "bitcoin/testnet-handshake"
  - "bitcoin/testnet-rejected_tx"
  - "bitcoin/regtest-bestblock"
  - "bitcoin/regtest-block"
  - "bitcoin/regtest-subtree"
  - "bitcoin/regtest-mining_on"
  - "bitcoin/regtest-handshake"
  - "bitcoin/regtest-rejected_tx"
  - "bitcoin/stn-bestblock"
  - "bitcoin/stn-block"
  - "bitcoin/stn-subtree"
  - "bitcoin/stn-mining_on"
  - "bitcoin/stn-handshake"
  - "bitcoin/stn-rejected_tx"
  - "bitcoin/teratestnet-bestblock"
  - "bitcoin/teratestnet-block"
  - "bitcoin/teratestnet-subtree"
  - "bitcoin/teratestnet-mining_on"
  - "bitcoin/teratestnet-handshake"
  - "bitcoin/teratestnet-rejected_tx"
  - "bitcoin/tstn-bestblock"
  - "bitcoin/tstn-block"
  - "bitcoin/tstn-subtree"
  - "bitcoin/tstn-mining_on"
  - "bitcoin/tstn-handshake"
  - "bitcoin/tstn-rejected_tx"
