apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: teranode

resources:
  - namespace.yaml
  - postgres.yaml
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: teranode-p2p
  app.kubernetes.io/part-of: teranode